services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env.backend
    networks:
      - clinic-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "3000:80"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge
